[workspace]
git_only = true
publish = false
release_always = false
changelog_path = "CHANGELOG.md"
repo_url = "https://github.com/Justkant/mv7mute"
pr_labels = ["release"]

[[package]]
name = "mv7mute"
git_release_enable = false
publish = false
