[workspace]
git_only = false
publish = false
release = false
release_always = true
publish_timeout = "10m"
repo_url = "https://github.com/Justkant/mv7mute"
pr_labels = ["release"]

[[package]]
name = "mv7mute"
release = true
git_only = true
git_tag_name = "v{{ version }}"
git_tag_enable = true
git_release_enable = false
publish = false
version_group = "apps"
changelog_path = "mv7mute/CHANGELOG.md"
changelog_include = ["mv7mute-core"]

[[package]]
name = "mv7mute-core"
release = true
git_only = false
git_tag_name = "mv7mute-core-v{{ version }}"
git_release_enable = false
publish = true
changelog_update = false

[[package]]
name = "mv7mute-tray"
release = true
git_only = true
git_tag_name = "v{{ version }}"
git_tag_enable = false
git_release_enable = false
publish = false
version_group = "apps"
changelog_path = "mv7mute-tray/CHANGELOG.md"
changelog_include = ["mv7mute-core"]
